config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "users/:id/dashboard", to: "pages#dashboard", as: :dashboard

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "services", to: "services#index", as: :services
  get "services/new", to: "services#new", as: :new_service
  post "services", to: "services#create"
  get "services/:id", to: "services#show", as: :service
  get "services/:id/edit", to: "services#edit", as: :edit_service
  patch "services/:id", to: "services#update"
  delete "services/:id", to: "services#destroy"



  patch "contracts/:id/update_status", to: "contracts#update_status", as: :update_status
  patch "contracts/:id/update_done", to: "contracts#done", as: :done

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "users/new", to: "users#new", as: :new_user
  post "users", to: "users#create"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"


  resources :users do
    resources :services do
      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
      end
    end
  end

  mount ActionCable.server => '/cable'

  resources :conversations do
    resources :messages
  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :contracts
  has_many :reviews, through: :contracts
  validates :category, presence: true

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/services_controller.rb
require 'csv'
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :set_reviews, only: [:show]
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:search].present? and params[:city].present?
      @services = Service.joins(:user).where('category ILIKE ? or city ILIKE ?', "%#{params[:search]}%", "%#{params[:city]}%")
    else
      if params[:search].present?
        @services = Service.where('category ILIKE ?', "%#{params[:search]}%")
      else
        @services = Service.all
      end

    end
    @markers = @services.geocoded.map do |service|
      {
        lat: service.latitude,
        lng: service.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { service: service })
      }
    end
  end

  def servdashboard
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
    @service = current_user.services.find(params[:id])
  end

  def create
    @service = current_user.services.create(service_params)
    if @service.save
      redirect_to dashboard_path(current_user)
    else
      render :new
    end
  end

  def update
    if @service.update(service_params)
      redirect_to dashboard_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @service.destroy

    redirect_to dashboard_path(current_user), status: :see_other
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def set_reviews
    @review = Review.where(service_id: @service.id)
  end

  def service_params
    params.require(:service).permit(:name_service, :description_service,
                                    :photo, :category, :price, :address, :user_id)
  end
end

app/views/services/_form.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center mt-4 mb-4 p-0">Add a Service</h2>
    <div class="col-12 col-md-6 offset-lg-3 mb-5">
      <div class="bg-white rounded p-3 shadow">
        <%= simple_form_for @service do |f| %>
          <%= f.input :name_service, label: 'Title', placeholder: 'Your service title' %>
          <%= f.input :description_service, :as => :text, :input_html => { class: 'test', :cols => 5, :rows => 8 }, label: 'Description', placeholder: 'Describe your service', class:"textarea" %>

          <%= f.input :category, collection: @categorys%>
          <%= f.input :photo, as: :file %>
          <%= f.input :address,
            input_html: {data: {address_autocomplete_target: "address"}},
            wrapper_html: {data: {controller: "address-autocomplete",
            address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
          %>
          <%= f.input :price, placeholder: '$' %>
          <%= f.button :submit, class:"btn-yellow"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/_index.html.erb
    <section>
      <div class="row">
        <div class="col-md-8">
          <% @services.each do |service| %>
          <% user = User.find(service.user_id)%>
          <div class="card">
            <div class="card-header">
              <%= service.name_service %>
            </div>
            <div class="card-body">
              <%= cl_image_tag service.photo.key, height: 300, width: 400, crop: :fill %>
                           <p><%= service.description_service %></p>
              <p><%= service.category %></p>
              <p><%= service.price %></p>
              <p><%= service.address %></p>
              <h1><%=user.email%></h1>

              <a href="#" class="btn btn-primary" style="border-radius: 5px; width: 100px">Contract</a>
            </div>
          </div>
          <% end %>
        </div>
      </div>

    </section>

    <%= link_to "New Service", new_service_path, class: "btn btn-primary" %>


    <style>
      .card {
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
      }

      .card-header {
        background-color: #f5f5f5;
        padding: 10px;
        border-bottom: 1px solid #ccc;
      }

      .card-body {
        padding: 10px;
      }

      .btn {
        margin-top: 10px;
      }
    </style>

app/views/services/_info_window.html.erb
<h4><%= service.name_service %></h4>
<p>Address: <%= service.address %></p>
<p>Price: <%= service.price %></p>

app/views/services/_my_services.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-8 w-100 px-0">
      <% @services.each do |service| %>
        <div class="card-my-services my-4">
          <% user = User.find(service.user_id)%>
            <div class="service-body d-flex">

              <div class="service-ph my-auto">
                <% if service.photo.attached? %>
                  <%= cl_image_tag service.photo.key, height: 200, width: 200, crop: :fill %>
                <% else %>
                  <%= image_tag "yellow_pages_bw_logo", class: "img-bw" %>
                <% end %>
              </div>

              <div class="service-info ms-4">
                <p class="tag-yellow mb-1"><%= service.category %></p>
                <div class="title-service">
                  <%= service.name_service %>
                </div>

                <p><%= service.address %></p>
                <p class="pt-1 mt-2 mb-3"><%= service.description_service %></p>
                <h4 class="mt-4 mb-3"><b>$ <%= service.price %></b></h4>

                <div class="service-btn d-flex">
                <%= link_to "Edit Service", edit_service_path(service.id), class: "btn-yellow" %>
                <%= button_to "Delete", service_path(service.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn-red-outline ms-2" %>

                </div>
              </div>

            </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/services/_show.html.erb
<h1>Services#show</h1>
<p>Find me in app/views/services/show.html.erb</p>

app/views/services/edit.html.erb
<%= render "form", service: @service %>

app/views/services/index.html.erb
<section class="container">
  <div class="row">

    <div class="title mt-4">
      <% if params[:search].blank? && params[:city].blank? %>
        <h2>All services (<%= @services.count %> results)</h2>
      <% elsif params[:search].present? && params[:city].blank? %>
        <h2><%= params[:search].capitalize %> (<%= @services.count %> results)</h2>
      <% elsif params[:city].present? && params[:search].blank? %>
        <h2>Services in <%= params[:city].capitalize %> (<%= @services.count %> results)</h2>
      <% else %>
        <h2><%= params[:search].capitalize %> in <%= params[:city].capitalize %> (<%= @services.count %> results)</h2>
      <% end %>
    </div>

    <div class="content mx-0 d-flex justify-content-between">

      <div class="col-md-8 px-0">
        <% @services.each do |service| %>
          <div class="card-services my-4">
            <% user = User.find(service.user_id)%>

            <div class="service-body d-flex">

              <div class="service-ph my-auto">
                <% if service.photo.attached? %>
                  <%= cl_image_tag service.photo.key, height: 200, width: 200, crop: :fill %>
                <% else %>
                  <%= image_tag "yellow_pages_bw_logo", class: "img-bw" %>
                <% end %>
              </div>

              <div class="service-info ms-4">
                <p class="tag-yellow mb-1"><%= service.category %></p>
                <div class="title-service">
                  <%= service.name_service %>
                </div>

                <p><%= service.address %></p>
                <p class="pt-2"><%= service.description_service %></p>
                <h4 class="mt-4 mb-3"><b>$ <%= service.price %></b></h4>

                <div class="service-btn">
                  <% if user_signed_in? %>
                    <%= link_to "Hire",  new_user_service_contract_path(user_id: current_user, service_id: service), class: "btn-yellow" %> <%# redireciona o usuário para a new de contrato %>
                    <%= link_to "Message", conversations_path(sender_id: current_user.id, recipient_id: user.id), data: { "turbo-method": :get }, class:"btn-yellow-outline ms-1" %>
                    <%= link_to "More Info", service_path(service.id), class:"btn-yellow-outline ms-1" %>
                  <% else %>
                    <%= link_to "Hire", new_user_session_path, class: "btn-yellow" %>
                    <%= link_to "Message", new_user_session_path, class: "btn-yellow-outline ms-1" %>
                    <%= link_to "More Info", service_path(service.id), class:"btn-yellow-outline ms-1" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>


      <div class="search my-4">

          <div class ="geo" style="width: 100%; height: 350px;"
                        data-controller="map"
                        data-map-markers-value="<%= @markers.to_json %>"
                        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>

          <div class="filter mt-3">
            <h6><i class="fa-solid fa-filter"></i> Filter by:</h6>
            <%= form_tag services_path, method: :get do %>

              <div class="form-group">
                <% Service.pluck(:category).uniq.each do |category| %>
                  <div class="form-check">
                    <%= radio_button_tag "search", category, params[:search] == category, id: "category_#{category.parameterize}" %>
                    <%= label_tag "category_#{category.parameterize}", category %>
                  </div>

                <% end %>
              </div>

              <div class="form-group">
                <%= submit_tag "Search", class: "btn-yellow-outline mt-3 w-100" %>
              </div>
            <% end %>
          </div>

      </div>
    </div>
  </div>
</section>

app/views/services/new.html.erb
<%= render "form", service: @service %>

app/views/services/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 px-0 w-100 my-4">
      <div class="card-my-services my-4">

        <div class="service-body">

          <div class="service-ph my-auto d-flex justify-content-center">
            <% if @service.photo.attached? %>
              <%= cl_image_tag @service.photo.key, height: 300, width: 1100, crop: :fill %>
            <% end %>
          </div>

          <div class="service-info ms-auto p-3">

            <p class="tag-yellow mb-1"><%= @service.category %></p>
            <div class="title-service">
                <%= @service.name_service %>
            </div>

            <% user = User.find(@service.user_id)%>
            <p class="mb-0">Service provider: <%= user.first_name %> <%= user.last_name %></p>
            <p><%= @service.address %></p>

            <p class="pt-2 mb-0">Description:</p>
            <p><%= @service.description_service %></p>
            <h4 class="mb-3">$ <%= @service.price %></h4>

            <div class="service-btn">
              <% if user_signed_in? %>
                <%= link_to "Hire",  new_user_service_contract_path(user_id: current_user, service_id: @service), class: "btn-yellow" %> <%# redireciona o usuário para a new de contrato %>
                <%= link_to "Message", conversations_path(sender_id: current_user, recipient_id: user), data: { "turbo-method": :post }, class:"btn-yellow-outline ms-1" %>
              <% else %>
                <%= link_to "Hire", new_user_session_path, class: "btn-yellow" %>
                <%= link_to "Message", new_user_session_path, class: "btn-yellow-outline ms-1" %>
              <% end %>
            </div>

          </div>
        </div>
      </div>

      <div class="mt-2 card-my-services p-4">
        <p class="title-reviews mb-3">See what people think about this service</p>

        <div class="card-body d-flex flex-column">

          <% if @service.reviews.any? %>
          <div class="img me-3 d-flex align-items-center">
            <% if @service.reviews.sample.contract.user.photo.attached? %>
              <%= cl_image_tag @service.reviews.sample.contract.user.photo.key, class: "avatar me-2 my-auto", width: 30, height: 30 %>
            <% end %>
            <p class="mb-0"><%= @service.reviews.sample.contract.user.first_name %> <%= @service.reviews.sample.contract.user.last_name %></p>
          </div>

          <div class="review">
            </h5><i class="fa-solid fa-star mt-2"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
            <p class="mt-2"><%= @service.reviews.sample.comment %></p>
          </div>
          <% else %>
            <p>No reviews yet.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>