config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "users/:id/dashboard", to: "pages#dashboard", as: :dashboard

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "services", to: "services#index", as: :services
  get "services/new", to: "services#new", as: :new_service
  post "services", to: "services#create"
  get "services/:id", to: "services#show", as: :service
  get "services/:id/edit", to: "services#edit", as: :edit_service
  patch "services/:id", to: "services#update"
  delete "services/:id", to: "services#destroy"



  patch "contracts/:id/update_status", to: "contracts#update_status", as: :update_status
  patch "contracts/:id/update_done", to: "contracts#done", as: :done

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "users/new", to: "users#new", as: :new_user
  post "users", to: "users#create"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"


  resources :users do
    resources :services do
      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
      end
    end
  end

  mount ActionCable.server => '/cable'

  resources :conversations do
    resources :messages
  end
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_one :review
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: [:index, :new, :create,:show]
  before_action :set_contract, only: [:show, :edit, :update, :done, :update_status, :done]


  def index
    @contracts = Contract.where('user_id = ? AND service_id IN (?)', current_user.id, current_user.services.pluck(:id))
  end

  def show
    user_id = current_user.id
    @user = current_user
    @customer_contracts = Contract.where(user_id: user_id)
    @provider_contracts = Contract.where(service_id: current_user.services.pluck(:id))

    # Combine os contratos do cliente e do prestador de serviços em uma única coleção
    @contracts = @customer_contracts.or(@provider_contracts)
  end

  def new
    @user = User.find(params[:user_id])
    @contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)
    @contract.user = current_user # Atribuindo o usuário logado ao contrato
    @contract.service = @service # Atribuindo o serviço ao contrato
    @contract.status = 'Pending' # Definindo o status de aceitação do contrato pelo usuário prestador do serviço
    @contract.done = false # Definindo o status de conclusão do contrato
    @new_contract_created = true

    if @contract.save
      redirect_to user_service_contract_path(user_id: @contract.user.id, service_id: @contract.service.id, id: @contract.id), notice: 'contract created successfully!'
    else
      render :new, status: :unprocessable_entity, notice: 'Unable to create contract.'
    end
  end

  def update_status
    @contract.status = params[:status]

    if @contract.save
      redirect_to dashboard_path(@contract)
    else
      redirect_to user_service_contract_path(contract.service.id)
    end
  end

  def edit
    render :show
  end

  def update
    @contract = Contract.find(params[:id])
    new_status = params[:status] # 'accept' ou 'reject'

    if current_user.id == @contract.service.user_id # Verifica se o usuário logado é o prestador do serviço
      if @contract.update(status: new_status)
        redirect_to dashboard_path(@contract), notice: 'Contract updated successfully.'
      else
        render :edit
      end
    else
      redirect_to dashboard_path(@contract), notice: 'You are not permitted to change this agreement.'
    end
  end

  # Ação personalizada para marcar o contrato como concluído
  def done
    @contract.done = true
    if @contract.save
      redirect_to dashboard_path(@contract)
    else
      redirect_to user_service_contract_path(contract.service.id)
    end
  end

  private

  def contract_params
    params.require(:contract).permit(:user_id, :service_id, :date, :status, :done)
  end

  def set_service
    @service = Service.find(params[:service_id])
  end

  def set_contract
    @contract = Contract.find(params[:id])
  end
end

app/views/contracts/_my_contracts.html.erb
<div class="container">

  <div class="card-body">
    <% @contracts = Contract.where('user_id = ? OR service_id IN (?)', current_user.id, current_user.services.pluck(:id)) %>

    <div class="title-contract text-center ms-3">
      <%= "Contracts as a customer" %>
    </div>

    <div class="customer d-flex flex-wrap">
    <% if @contracts.present? && @contracts.any? %>
      <% customer_contracts = @contracts.select { |contract| current_user.id == contract.user.id } %>

      <% if customer_contracts.present? %>
        <% customer_contracts.each do |contract| %>
        <div class="card-contracts p-4 mx-auto">

          <p class="title pt-2 border-bottom mb-3"><strong><%= "Service: "%></strong> <%= "#{contract.service.name_service}" %></p>
          <p><strong><%= "Description: " %></strong> <%= "#{contract.service.description_service}" %></p>
          <p><strong><%= "Service provider: " %></strong> <%= "#{contract.service.user.first_name} #{contract.service.user.last_name}" %></p>
          <p><strong><%= "Date: " %></strong> <%= "#{contract.date}" %></p>

          <% if contract.status == 'Pending' %>
              <p class="d-inline-flex"><strong><%= "Status: "%></strong><p class="d-inline-flex p-1 ms-1 border border-warning text-warning"><%= "#{contract.status}" %></p></p>
            <% elsif contract.status == 'Accepted' %>
              <p class="d-inline-flex"><strong><%= "Status: "%></strong><p class="d-inline-flex p-1 ms-1 border border-success text-success"><%= "#{contract.status}" %></p></p>
          <% else %>
              <p class="d-inline-flex"><strong><%= "Status: "%></strong><p class="d-inline-flex p-1 ms-1 border border-danger text-danger"><%= "#{contract.status}" %></p></p>
          <% end %>


            <%= link_to "See more details", user_service_contract_path(user_id: contract.user.id, service_id: contract.service.id, id: contract.id), class:'btn-yellow-outline w-100' %>
        </div>
      <% end %>

  </div>
      <% else %>
          <div class="card-contracts p-4 w-100">
            <p class="d-flex mb-0">You have 0 contracts as a customer</p>
          </div>

      <% end %>
    <% else %>
    <div class="card-contracts p-4 w-100">
      <p class="mb-0">No contracts available</p>
    </div>
    <% end %>
</div>




  <div class="title-contract text-center border-top mt-3">
    <%= "Contracts as a service provider" %>
  </div>

  <div class="provider">
    <% if @contracts.present? && @contracts.any? %>
      <% provider_contracts = @contracts.select { |contract| current_user.id == contract.service.user.id } %>

      <% if provider_contracts.present? %>
        <% provider_contracts.each do |contract| %>

          <div class="card-contracts p-4 mx-auto">

            <p class="title pt-2 border-bottom mb-3"><strong><%= "Service: " %></strong> <%= "#{contract.service.name_service}" %></p>
            <p><strong><%= "Description: " %></strong> <%= "#{contract.service.description_service}" %></p>
            <p><strong><%= "Client: " %></strong> <%= " #{contract.user.first_name} #{contract.user.last_name}" %></p>
            <p><strong><%= "Date: "%></strong> <%= "#{contract.date}" %></p>

            <% if contract.status == 'Pending' %>
              <p class="d-inline-flex"><strong><%= "Status: " %></strong> <p class="d-inline-flex p-1 ms-1 border border-warning text-warning mb-0"><%= "#{contract.status}" %></p></p>
            <% elsif contract.status == 'Accepted' %>
              <p class="d-inline-flex"><strong><%= "Status: " %></strong> <p class="d-inline-flex p-1 ms-1 border border-success text-success mb-0"><%= "#{contract.status}" %></p></p>
            <% else %>
              <p class="d-inline-flex"><strong><%= "Status: " %></strong> <p class="d-inline-flex p-1 ms-1 border border-danger text-danger mb-0"><%= "#{contract.status}" %></p></p>
            <% end %>

            <%= link_to "See more details", user_service_contract_path(user_id: contract.user.id, service_id: contract.service.id, id: contract.id), class:'btn-yellow-outline w-100' %>
          </div>
        <% end %>
      <% else %>

      <div class="card-contracts p-4 w-100">
        <p class="mb-0">You have 0 contracts as a service provider</p>
      </div>
    <% end %>
    <% else %>
      <div class="card-contracts p-4 w-100">
        <p>No contracts available</p>
      </div>
    <% end %>
    </div>
  </div>

app/views/contracts/index.html.erb
<div class="container">
    <% @contracts.each do |contract| %>
      <div class="card">
        <h3>Contracts as a customer</h3>

        <% if current_user.id == contract.user.id %>
          <p><%= contract.service.name_service %></p>
          <p><%= contract.service.description_service %></p>
          <p><%= contract.service.user.first_name %> <%= contract.service.user.last_name %></p>
          <p><%= contract.status %></p>
          <p><%= contract.date %></p>
          <%= link_to "See more details", service_contract_path(service_id: contract.service.id, id: contract.id) %>
        <% else %>
          <p>You have no contracts</p>
        <% end %>

      <h3>Contracts as a service provider</h3>

      <% if current_user.id == contract.service.user.id %>
        <p><%= contract.service.name_service %></p>
        <p><%= contract.service.description_service %></p>
        <p><%= contract.user.first_name %></p>
        <p><%= contract.status %></p>

        <%= link_to "See more details", service_contract_path(contract.service.id) %>
      <% else %>
        <p>You have no contracts</p>
      <% end %>
  <% end %>
</div>

app/views/contracts/new.html.erb
<div class="container">
  <h2 class="text-center mt-4 mb-0">Select a date</h2>
  <div class="devise-card mt-4 mb-5 mx-auto">
    <%= simple_form_for [@user, @service, @contract] do |f| %>
    <%= f.input :date, as: :date, label: 'Date of the service:', start_year: Date.today.year, end_year: Date.today.year + 1 %>
    <%= f.button :submit, class:"btn-yellow" %>

  <% end %>
  </div>
</div>

app/views/contracts/show.html.erb
            <div class="item">

              <h2 class="text-center mt-4 mb-4">Contract Details</h2>
              <div class="container mt-4 mb-5 contract-box">

                <% if @new_contract_created %>
                  <div class="alert alert-success" role="alert">
                    <h4 class="alert-heading">Congratulations!</h4>
                      <p>Your contract has been created successfully! If you want to review the information of your contract visit your dashboard.</p>
                  </div>
                <% end %>

                <% if @contract && @user %>

                  <div class="contract-info">

                    <p class="mb-3"><strong class="contract-bold">Client:</strong> <%= @contract.user.first_name %> <%= @contract.user.last_name %></p>
                    <p class="border-top mb-3 pt-3"><strong class="contract-bold">Contracted Service:</strong> <%= @contract.service.name_service %></p>
                    <p class="border-top mb-3 pt-3"><strong class="contract-bold">Service Provider:</strong> <%= @contract.service.user.first_name %> <%= @contract.service.user.last_name %></p>
                    <p class="border-top mb-3 pt-3"><strong class="contract-bold">Date of Service:</strong> <%= @contract.date %></p>
                    <p class="border-top mb-3 pt-3"><strong class="contract-bold">Service Price:</strong> $ <%= @contract.service.price %></p>

                    <div class="border-top mb-3 pt-3">
                    <% if @contract.status == "Pending" %>
                      <p class="d-inline-flex"><strong class="contract-bold">Service Status:</strong> <p class="d-inline-flex p-2 ms-2 mb-0 border border-warning text-warning"><%= @contract.status %></p></p>
                    <% elsif @contract.status == "Accepted" %>
                      <p class="d-inline-flex"><strong class="contract-bold">Service Status:</strong> <p class="d-inline-flex p-2 ms-2 mb-0 border border-success text-success"><%= @contract.status %></p></p>
                    <% else %>
                      <p class="d-inline-flex "><strong class="contract-bold">Service Status:</strong> <p class="d-inline-flex p-2 ms-2 mb-0 border border-danger text-danger"><%= @contract.status %></p></p>
                    <% end %>

                    <% if @contract.user == current_user && @contract.status != 'Pending' %> <!-- Verifica se o usuário é o cliente -->
                      <div class="d-flex align-items-center">
                        <p class="my-auto"><strong class="contract-bold">Has the contract been completed?</strong></p>
                        <% if @contract.done == true %>
                          <p class="d-inline-flex"><p class="d-inline-flex p-2 ms-2 mb-0 border border-success text-success">Yes</p></p>
                        <% else %>
                          <%= button_to 'Yes', done_path(@contract), method: :patch, data: { "turbo-method": :patch }, class: "btn-green mx-3" %>
                        <% end %>
                      </div>
                    <% end %>

                    <% if @contract.status == 'Pending' && @contract.service.user == current_user %> <!-- Verifica se o contrato ainda esta pendete e se o usuário é o prestador de serviços -->
                      <div class="d-flex align-items-center mt-2">
                        <p class="my-auto"><strong class="contract-bold">Do you accept the contract?</strong></p>
                        <%= button_to 'Yes', update_status_path(id: @contract.id, status: 'Accepted'), method: :patch, data: { "turbo-method": :patch }, class: "btn-green mx-2" %>
                        <%= button_to 'No', update_status_path(id: @contract.id, status: 'Rejected'), method: :patch, data: { "turbo-method": :patch }, class: "btn-red" %>
                      </div>
                    <% end %>
                  </div>
                  </div>

                  <%# só aparece o botao de deixar review se o contrato tiver sido done e o user for o cliente %>
                  <div class="d-flex text-center justify-content-center">
                    <% if @contract.done != true && @contract.service.user != current_user %>
                      <%= link_to "Leave a Review", new_user_service_contract_review_path(user_id: @contract.user.id, service_id: @contract.service.id, contract_id: @contract.id), class: "btn disabled btn-yellow mt-4" %>
                      <%= link_to 'Back to dashboard', dashboard_path(id: @contract.id), class: "btn-yellow mt-4 ms-2" %>
                    <% elsif @contract.done == true && @contract.service.user != current_user %>
                      <%= link_to "Leave a Review", new_user_service_contract_review_path(user_id: @contract.user.id, service_id: @contract.service.id, contract_id: @contract.id), class: "btn-yellow mt-4" %>
                      <%= link_to 'Back to dashboard', dashboard_path(id: @contract.id), class: "btn-yellow mt-4 ms-2" %>
                    <% else %>
                      <%= link_to 'Back to dashboard', dashboard_path(id: @contract.id), class: "btn-yellow mt-4 ms-2" %>
                    <% end %>
                  </div>

                <% else %>
                  <p>Contract not found.</p>
                <% end %>
              </div>