config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "users/:id/dashboard", to: "pages#dashboard", as: :dashboard

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "services", to: "services#index", as: :services
  get "services/new", to: "services#new", as: :new_service
  post "services", to: "services#create"
  get "services/:id", to: "services#show", as: :service
  get "services/:id/edit", to: "services#edit", as: :edit_service
  patch "services/:id", to: "services#update"
  delete "services/:id", to: "services#destroy"



  patch "contracts/:id/update_status", to: "contracts#update_status", as: :update_status
  patch "contracts/:id/update_done", to: "contracts#done", as: :done

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "users/new", to: "users#new", as: :new_user
  post "users", to: "users#create"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"


  resources :users do
    resources :services do
      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
      end
    end
  end

  mount ActionCable.server => '/cable'

  resources :conversations do
    resources :messages
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :services
  has_many :contracts
  has_many :reviews, through: :services
  has_one_attached :photo


  validates :email, uniqueness: true
  has_many :conversations, foreign_key: :sender_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :new
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # If the user is saved successfully, redirect to the user's show page
    if @user.save
      redirect_to @user
    else
      # If the user isn't saved successfully, re-render the form so the user can fix the problems
      flash.now[:alert] = 'There was a problem creating the User.'
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to dashboard_path(current_user)
    else
      flash.now[:alert] = 'There was a problem updating the User.'
      @errors = @user.errors.full_messages
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :city, :state, :phone, :photo, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at)
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <div class="name d-flex justify-content-between">
    <%= f.input :first_name, required: true %>
    <%= f.input :last_name, required: true %>
  </div>
  <%= f.input :photo, as: :file %>
  <%= f.input :city, required: true %>
  <%= f.input :state, required: true %>
  <%= f.input :phone, required: true %>

  <%= f.button :submit, "Update", class:"btn-yellow" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="text-center mt-4 mb-0">Edit Profile</h2>
  <div class="devise-card mt-4 mb-5 mx-auto">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/new.html.erb
<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% end %>

<% if @errors %>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<p>Email: <%= @user.email %></p>
<p>City: <%= @user.city %></p>
<p>State: <%= @user.state %></p>
<p>Phone: <%= @user.phone %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>