config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "users/:id/dashboard", to: "pages#dashboard", as: :dashboard

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "services", to: "services#index", as: :services
  get "services/new", to: "services#new", as: :new_service
  post "services", to: "services#create"
  get "services/:id", to: "services#show", as: :service
  get "services/:id/edit", to: "services#edit", as: :edit_service
  patch "services/:id", to: "services#update"
  delete "services/:id", to: "services#destroy"



  patch "contracts/:id/update_status", to: "contracts#update_status", as: :update_status
  patch "contracts/:id/update_done", to: "contracts#done", as: :done

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "users/new", to: "users#new", as: :new_user
  post "users", to: "users#create"
  get "users/:id", to: "users#show", as: :user
  get "users/:id/edit", to: "users#edit", as: :edit_user
  patch "users/:id", to: "users#update"


  resources :users do
    resources :services do
      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
      end
    end
  end

  mount ActionCable.server => '/cable'

  resources :conversations do
    resources :messages
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p class="pt-2">Yellow Pages © 2024</p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon text-center">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <div class="d-flex">
        <%= image_tag "yellow_pages_logo.png" %>
        <p class="logo-name ms-2 mb-0">yellow pages</p>
      </div>
    <% end %>

    <% unless current_page?(root_path) %>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <form class="form d-flex mx-auto" action="/services" method="get">
              <input class="form-control me-2" type="text" name="search" placeholder="Category" aria-label="Search">
              <input class="form-control me-2" type="text" name="city" placeholder="City" aria-label="Search">
              <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
          </div>
        </div>
      </div>
    <% end %>
    <div class="notifications"></div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-content-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Message", conversations_path(sender_id: current_user.id, recipient_id: current_user.id), data: { "turbo-method": :get }, class: "nav-link me-2"%>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? && current_user.photo.key.present? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "default_avatar.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New Service", new_user_service_path(user_id: current_user.id), class: "dropdown-item" %> <%# alterado %>
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item-btn d-flex">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-dark ms-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>